def cls():
    for i in range(15):
        print('')


cls()
print('1. Wie sieht der Code für ein Leeres Dictionary aus?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Ein Dictionary definiert man mit "name={}"')
print('\n\n\n\n')
input()

cls()
print('2. Wie sieht ein Dictionary mit dem Schlüssel "foo" und dem Wert 42 aus?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('name={\'foo\' : 42}')
print('\n\n\n\n')
input()

cls()
print('3. Was ist der Hauptunterschied zwischen einem Dictionary und einer Liste?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Listen können Sortiert werden während Dictionarys zu jedem Eintrag \neinen korrespondierenden String oder Wert speichern kann.')
print('\n\n\n\n')
input()

cls()
print('4. Was passiert wenn sie versuchen "spam[\'foo\']" \nund spam den Wert {\'bar\' : 100} hat?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Es wird ein KeyError ausgegeben da kein Schlüssel mit dem Namen "foo" vorhanden ist')
print('\n\n\n\n')
input()

cls()
print('5. Was ist der Unterschied zwischen "\'cat\' in spam" \nund "\'cat\' in spam.keys()?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Im Grunde überprüfen beide Beispiele ob der "cat" als Schlüssel vorhanden ist.\nBei Listen in Dictionarys kann .keys() verwendet werden um nur die einzelnen Namen der\nDictionarys anzuzeigen')
print('\n\n\n\n')
input()

cls()
print('6. Was ist der Unterschied zwischen "\'cat\' in spam" \nund "\'cat\' in spam.values()?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Beim 1. Beispiel werden die Schlüssel überprüft ob "cat" vorhanden ist.\nIm 2. Beispiel wird geprüft ob "cat" als Wert eines Sclüssels eingetragen ist.\n Beide Varianten geben True oder False aus.')
print('\n\n\n\n')
input()

cls()
print('7. Wie können sie folgenden Code kürzer fassen?')
print('')
print('if \'color\' not in spam:')
print('    spam[\'color\'] = \'black\'')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Mit der setdefault() Methode kann man die Prüfung direkt integrieren. \n\n spam.setdefault(\'color\', \'black\')\n')
print('\n\n\n\n')
input()

cls()
print('8. Welche Module und Funktionen können sie Bei Dictionarys anwenden?')
print('\n\n\n\n')
input()
print('\n\n\n\n')
print('Funktionen: name.setdefault() name.values(), name.keys(), name.items()\nModule: pprint')
print('\n\n\n\n')
input()
