/*Verwendung des INSERT-Statements*/
/*https://www.oracletutorial.com/oracle-basics/oracle-insert/*/

DROP TABLE discounts PURGE;

CREATE TABLE discounts (
       discount_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
       discount_name VARCHAR2(255) NOT NULL,
       amount NUMBER(3,1) NOT NULL, 
       start_date DATE NOT NULL,
       expired_date DATE NOT NULL );

/*Add row to table*/
INSERT INTO discounts(discount_name, amount, start_date, expired_date)
VALUES('Summer Promotion 2017', 9.5, DATE '2017-05-01', DATE '2017-08-31');

INSERT INTO discounts(discount_name, amount, start_date, expired_date)
VALUES('Winter Promotion 2017', 10.5, DATE '2017-12-01', DATE '2017-12-31');
COMMIT;

SELECT * FROM discounts;
