/*Partielles einfüllen von Daten*/
/*https://www.oracletutorial.com/oracle-basics/oracle-insert-into-select/*/

DROP TABLE customer_lists PURGE;

CREATE TABLE customer_lists(
       list_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
       first_name varchar2(255) NOT NULL,
       last_name varchar2(255) NOT NULL, 
       email varchar2(255) NOT NULL,
       sent NUMBER(1) NOT NULL,
       sent_date DATE,
       PRIMARY KEY(list_id)
);

INSERT INTO customer_lists(
       first_name, last_name, email, sent)
       SELECT first_name, last_name, email, 0
       FROM contacts;
       
SELECT * FROM customer_lists;
       
