/*RENAME TABLE Beispiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-rename-table/*/

CREATE TABLE promotions(
    promotion_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    promotion_name varchar2(255),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    PRIMARY KEY(promotion_id),
    CHECK (end_date > start_date)
);

/*Tabelle umbenennen*/
RENAME promotions TO campaigns;

CREATE OR REPLACE FUNCTION count_promotions
       RETURN NUMBER
IS
       v_count NUMBER
BEGIN SELECT COUNT(*) INTO v_count FROM promotions;
      RETURN v_count;
END;

DROP TABLE campaigns PURGE;
