/*Überführen von Daten in eine neue Tabelle*/
/*https://www.oracletutorial.com/oracle-basics/oracle-exists/*/

/*Wenn Tabelle existiert, lösche diese und erstelle neue Tabelle*/
--select * from sys.user_tables

DROP TABLE customers_2016 PURGE;

CREATE TABLE customers_2016(
       company_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
       company varchar2(255) NOT NULL,
       first_name varchar(255) NOT NULL,
       last_name varchar(255) NOT NULL,
       email varchar(255) NOT NULL, 
       sent_email CHAR(1) DEFAULT 'N',
       PRIMARY KEY(company_id)
);

INSERT INTO customers_2016(
       company, first_name, last_name, email)
       SELECT name company, first_name, last_name, email
              FROM customers c
              INNER JOIN contacts ON contacts.customer_id = c.customer_id
              WHERE EXISTS (
                    SELECT * FROM orders
                    WHERE customer_id = c.customer_id 
                    AND EXTRACT(YEAR FROM order_date) = 2016 )
              ORDER BY company;

COMMIT;
