/*TRUNCATE TABLE Beispiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-truncate-table/*/

DROP TABLE quotations PURGE;
DROP TABLE quotation_items PURGE;
DROP TABLE customers_copy PURGE;

CREATE TABLE customers_copy AS SELECT * FROM customers;

TRUNCATE TABLE customers_copy;

/*Beispiel für TRUNCADTE TABLE CASCADE*/
CREATE TABLE quotations (
    quotation_no NUMERIC GENERATED BY DEFAULT AS IDENTITY,
    customer_id NUMERIC NOT NULL,
    valid_from DATE NOT NULL,
    valid_to DATE NOT NULL,
    PRIMARY KEY(quotation_no)
);
 
CREATE TABLE quotation_items (
    quotation_no NUMERIC,
    item_no NUMERIC ,
    product_id NUMERIC NOT NULL,
    qty NUMERIC NOT NULL,
    price NUMERIC(9 , 2 ) NOT NULL,
    PRIMARY KEY (quotation_no , item_no),
    CONSTRAINT fk_quotation FOREIGN KEY (quotation_no)
        REFERENCES quotations
        ON DELETE CASCADE
);

INSERT INTO quotations(customer_id, valid_from, valid_to)
VALUES(100, DATE '2017-09-01', DATE '2017-12-01');
 
INSERT INTO quotation_items(quotation_no, item_no, product_id, qty, price)
VALUES(1,1,1001,10,90.5);
 
INSERT INTO quotation_items(quotation_no, item_no, product_id, qty, price)
VALUES(1,2,1002,20,200.5);
 
INSERT INTO quotation_items(quotation_no, item_no, product_id, qty, price)
VALUES(1,3,1003,30, 150.5);

/*Löschen von Einträgen und deren Verknüpfungen*/
TRUNCATE TABLE quotations CASCADE;

SELECT * FROM quotations
