/*UNIQUE CONSTRAINT Beispiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-unique-constraint/*/

/*Beispiel*/
-- CREATE TABLE table_name (
--     ...
--     column_name data_type UNIQUE  -- Jeder Eintrag muss einzigartig sein. Es sind keine Doppelten Werte in dieser Spalte erlaubt.
--     ...
-- );

CREATE TABLE clients( 
       client_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
       first_name VARCHAR2(255) NOT NULL,
       last_name VARCHAR2(255) NOT NULL,
       company_name VARCHAR2(255) NOT NULL,
       email VARCHAR2(255) NOT NULL UNIQUE, -- Muss einzigartig sein
       phone VARCHAR(25)
);

INSERT INTO clients(first_name,last_name, email, company_name, phone)
VALUES('Christene','Snider','christene.snider@abc.com', 'ABC Inc', '408-875-6075');

/*Möchte man einen doppelten Wert eintragen wird eine Fehlermeldung ausgelöst*/
INSERT INTO clients(first_name,last_name, email, company_name, phone)
VALUES('Sherly','Snider','christene.snider@abc.com', 'ABC Inc', '408-875-6076');

/*Hinzufügen von UNIQUE CONSTRAINTS*/
ALTER TABLE clients
ADD CONSTRAINT unique_company_phone UNIQUE(company_name, phone);

/*Deaktivieren von UNIQUE CONSTRAINTS*/
ALTER TABLE clients
DISABLE CONSTRAINT unique_company_phone;

/*Reaktivieren von inaktiven UNIQUE CONSTRAINTS*/
ALTER TABLE clients
ENABLE CONSTRAINT unique_company_phone;

/*Löschen nicht benötigter UNIQUE CONSTRAINTS*/
ALTER TABLE clients
DROP CONSTRAINT unique_company_phone;





DROP TABLE clients PURGE;
       
