/*FOREIGN KEY Beispiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-foreign-key/*/

-- Parent Table
CREATE TABLE supplier_groups(
    group_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    group_name VARCHAR2(255) NOT NULL,
    PRIMARY KEY (group_id)  
);
 
-- Child Table
CREATE TABLE suppliers (
    supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    supplier_name VARCHAR2(255) NOT NULL,
    group_id NUMBER NOT NULL,
    PRIMARY KEY(supplier_id),
    FOREIGN KEY(group_id) REFERENCES supplier_groups(group_id) -- Referenz zwischen den Tabellen supplier_group und dieser
    ON DELETE CASCADE -- Löscht Daten die zusammenhängen um Datenleichen zu vermeiden sinnvoll. 
);

/*Tabelle mit Werten befüllen*/
INSERT INTO supplier_groups(group_name)
VALUES('One-time Supplier');
 
INSERT INTO supplier_groups(group_name)
VALUES('Third-party Supplier');
 
INSERT INTO supplier_groups(group_name)
VALUES('Inter-co Supplier');


/*Durch die Verknüpfung ist es nicht mehr möglich eine Group_ID zu verwenden die nicht in der Parent-Table
referenziert wurde.*/
INSERT INTO suppliers(supplier_name, group_id)
VALUES('WD',4);

/*Es ist auch nicht möglich in der Parent-Table einträge zu löschen wenn sich noch verknüpfte Daten im Child Table befinden.*/
DELETE FROM supplier_groups
WHERE group_id = 1;

/*Auch beim Entfernen von Tabellen kommt die Verknüpfung zum tragen. Es kann vorerst nur die Child-Table und erst
danach die Parent-Tables gelöscht werden.*/
DROP TABLE suppliers PURGE;
DROP TABLE supplier_groups PURGE;
