/*Beispiele für ALTER TABLE ADD*/
/*https://www.oracletutorial.com/oracle-basics/oracle-alter-table-add-column/*/

DROP TABLE members PURGE;

CREATE TABLE members(
       member_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
       first_name VARCHAR2(50),
       last_name VARCHAR2(50),
       PRIMARY KEY(member_id));
       
ALTER TABLE members
ADD birth_date DATE NOT NULL;

ALTER TABLE members
ADD(created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL);

SELECT COUNT(*) FROM user_tab_cols
WHERE column_name = 'FIRST_NAME' 
      AND table_name = 'MEMBERS';
          
    
SELECT * FROM members

