/*DROP Column Besipiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-drop-column/*/

DROP TABLE suppliers PURGE;

CREATE TABLE suppliers(
             supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
             contact_name VARCHAR2(255) NOT NULL,
             company_name VARCHAR2(255),
             phone VARCHAR2(100) NOT NULL,
             email VARCHAR2(255) NOT NULL,
             fax VARCHAR2(100) NOT NULL,
             PRIMARY KEY(supplier_id));
             
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Solomon F. Zamora', 'Elit LLP', '1-245-616-6781', 'enim.condimentum@pellentesqueeget.org', '1-593-653-6421');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Gail X. Tyson',' Vulputate Velit EU Inc.','1-331-448-8406','sem@gravidasit.edu','1-886-556-8494');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Alec N. Strickland','In At Associates',   '1-467-132-4527','Lorem@sedtortor.com','1-735-818-0914');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Britanni Holt','Magna Cras Convallis Corp.','1-842-554-5106','varius@seddictumeleifend.ca','1-381-532-1632');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Audra O. Ingram','Commodo LLP','1-934-490-5667','dictum.augue.malesuada@idmagnaet.net','1-225-217-4699');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Cody K. Chapman','Tempor Arcu Inc.','1-349-383-6623','non.arcu.Vivamus@rutrumnon.co.uk','1-824-229-3521');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Tobias Merritt','Amet Risus Company','1-457-675-2547','felis@ut.net','1-404-101-9940');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Ryder G. Vega','Massa LLC','1-655-465-4319','dui.nec@convalliserateget.co.uk','1-282-381-9477');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Arthur Woods','Donec Elementum Lorem Foundation','1-406-810-9583','eros.turpis.non@anteMaecenasmi.co.uk','1-462-765-8157');
INSERT INTO suppliers(contact_name, company_name, phone, email, fax) VALUES ('Lael Snider','Ultricies Adipiscing Enim Corporation','1-252-634-4780','natoque.penatibus@in.com','1-986-508-6373');

/*Unbenutzte Spalte festlegen*/
ALTER TABLE suppliers SET UNUSED COLUMN fax;

/*Unbenutzte Spalten löschen*/
ALTER TABLE suppliers DROP UNUSED COLUMNS;

ALTER TABLE suppliers 
DROP ( email,
       phone );
       
/*Zeige alle unbenutzten Spalten an*/
select * from ALL_UNUSED_COL_TABS;


