/*NOT NULL Bespiele*/
/*https://www.oracletutorial.com/oracle-basics/oracle-not-null/*/

CREATE TABLE surcharges (
  surcharge_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
  surcharge_name VARCHAR2(255) NOT NULL,
  amount NUMBER(9,2),
  PRIMARY KEY (surcharge_id)
);

/*Einträge welche die NOT NULL Constraint einhalten können problemlos in die Tabelle übertragen werden*/
INSERT INTO surcharges(surcharge_name, amount)
VALUES('Late order placement',10);

/*Einträge die NULL-Values aufweisen verursachen jedoch eine Fehlermeldung*/
INSERT INTO surcharges(surcharge_name, amount)
VALUES(null,10);

/*Der Eintrag Amount akzeptiert NULL-Values und nimmt diese Fehlerfrei entgegen*/
INSERT INTO surcharges(surcharge_name, amount)
VALUES ('Rush Orders', null);

/*Anzeigen aller CONSTRAINTS dieser Tabelle*/
SELECT
    table_name,
    constraint_name,
    search_condition
FROM
    user_constraints
WHERE
    table_name = 'SURCHARGES';
    
/*Hinzufügen einer NOT NULL Constraint in eine bestehende Tabelle*/
ALTER TABLE surcharges
MODIFY (amount NOT NULL); -- Da bereits NULL-Values vorhanden sind wird diese Modifikation einen Fehler auslösen
                         -- Daher müssen die Null-Values erst entfernt/überschrieben werden

/*Überschreiben der Null-Values*/
UPDATE surcharges
SET amount = 0
WHERE amount IS NULL;

-- Nun kann die NOT NULL Constraint hinzugefügt werden. 
ALTER TABLE surcharges
MODIFY (amount NOT NULL);

/*Ändern einer Spalte um NULL-Values zu akzeptieren*/
ALTER TABLE surcharges
MODIFY (amount NULL);





DROP TABLE surcharges PURGE;
